import geoalchemy2
"""empty message

Revision ID: 96faa47d2963
Revises: 
Create Date: 2019-12-03 12:17:40.604378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96faa47d2963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baby__monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('smart__light',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('baby__monitor_main_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('send_interval', sa.String(), nullable=True),
    sa.Column('baby__monitor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby__monitor_id'], ['baby__monitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart__light_main_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('send_interval', sa.String(), nullable=True),
    sa.Column('smart__light_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['smart__light_id'], ['smart__light.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('baby__monitor_main_sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('breathing', sa.Boolean(), nullable=True),
    sa.Column('sleeping', sa.Boolean(), nullable=True),
    sa.Column('baby__monitor_main_sensor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby__monitor_main_sensor_id'], ['baby__monitor_main_sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart__light_main_sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('timeoff', sa.Boolean(), nullable=True),
    sa.Column('presence', sa.Boolean(), nullable=True),
    sa.Column('smart__light_main_sensor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['smart__light_main_sensor_id'], ['smart__light_main_sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smart__light_main_sensor_data')
    op.drop_table('baby__monitor_main_sensor_data')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('smart__light_main_sensor')
    op.drop_table('baby__monitor_main_sensor')
    op.drop_table('smart__light')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('baby__monitor')
    # ### end Alembic commands ###
